### ISSUE TITLE
how to adjust rewards in cfg.yaml

### ISSUE THREAD

**Issue by abdul-mannan-khan** [raisimTech/raisimLib#129]
Dear @jhwangbo  

How can I adjust the rewards in cfg.yaml? After going through your video [lecture on YouTube](https://www.youtube.com/watch?v=RoTYz_cqK7w&t=2147s) (Thanks for this lecture), I tried to understand `cfg.yaml`. I want to adjust rewards. In  cfg.yaml file, there is a reward tag which has forward velocity and torque reward coefficients as shown here below. 

```
seed: 1
record_video: yes

environment:
  render: True
# just testing commenting
  num_envs: 100
  eval_every_n: 200
  num_threads: 30
  simulation_dt: 0.0025
  control_dt: 0.01
  max_time: 4.0
  reward:
    forwardVel:
      coeff: 0.3
    torque:
      coeff: -4e-5

architecture:
  policy_net: [128, 128]
  value_net: [128, 128]
```

I am trying to understand forwardVel: coeff: 0.3 reward and torque reward. Are these the value I should adjust? Also, torque coefficient seems too small. Is there any particular reason? Thank you so much for your response.
